import type { Metadata } from "next";
import { inter } from "@/app/ui/fonts";
import "./globals.css";
import { ThemeProvider } from "@/components/utility/theme-provider";
import HomeHeader from "@/components/main-header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
                <HomeHeader />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
